import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";


export const metadata = {
  title: "intership project  Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      >
        {children}
      </body>
    </html>
  );
}
